import localFont from "next/font/local";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/OpenSans-VariableFont_wdth,wght.ttf", 
  variable: "--font-sans", 
  weight: "100 900", 
});

const geistCormorant = localFont({
  src: "./fonts/Cormorant-VariableFont_wght.ttf", 
  variable: "--font-cormorant", 
  weight: "100 900", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistCormorant.variable}`}>
      {children}
      </body>
    </html>
  );
}
